---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: paimon
spec:
  profile:
    displayName: Paimon
    email: paimon.soror@gmail.com
  memberOf: [sororlab]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sororlab
spec:
  type: team
  children: []
